---
title:               Seongsiks
tagline:             Being A DevOpser.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "kssminus" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "k36722427" %>
name:                Seongsik, Kim
twitter:             kssminus
github:              kssminus
email:               kssminus@gmail.com
disqus:              seongsiks
google_analytics_id: UA-39363299-1 
