---
title:               Seongsiks
tagline:             Being A Developer.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Seongsik, Kim
twitter:             kssminus
github:              kssminus
email:               kssminus@gmail.com
google_analytics_id: YOUR_GA_ID
